# Generated by Django 3.0.4 on 2020-04-01 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cmunicipio', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código de Municipio')),
                ('nombremunicipiocastellano', models.CharField(max_length=100, verbose_name='Nombre en castellano')),
                ('nombremunicipiolenguaoficial', models.CharField(max_length=100, verbose_name='Nombre en la lengua oficial')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprovincia', models.CharField(max_length=2, verbose_name='Código de Provincia')),
                ('nombreprovinciacastellano', models.CharField(max_length=100, verbose_name='Nombre en castellano')),
                ('nombreprovincialenguaoficial', models.CharField(max_length=100, verbose_name='Nombre en la lengua oficial')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('numero', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nif_nie', models.CharField(blank=True, max_length=9, verbose_name='NIF/NIE')),
                ('domicilio', models.CharField(blank=True, max_length=100, verbose_name='Domicilio')),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cuota')),
                ('periodo', models.CharField(choices=[('0', 'Mensual'), ('1', 'Trimestral'), ('2', 'Semestral'), ('3', 'Anual')], default='0', max_length=1, verbose_name='Periodo')),
                ('cmunicipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libiapp.Municipio', verbose_name='Municipio')),
                ('cprovincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libiapp.Provincia', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboDevuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(max_length=35, verbose_name='Referencia')),
                ('importe', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='Importe')),
                ('titular', models.CharField(max_length=100, verbose_name='Titular Domiciliación')),
                ('iban', models.CharField(max_length=24, verbose_name='IBAN')),
                ('motivo', models.CharField(choices=[('AC01', 'Número de IBAN incorrecto'), ('AC04', 'Número de cuenta cancelada'), ('AC06', 'Cuenta bloqueada')], max_length=4, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, max_length=300, verbose_name='Observaciones')),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libiapp.Socio')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='cprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libiapp.Provincia', verbose_name='Provincia'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('estado', models.CharField(blank=True, choices=[('a', 'Abierta'), ('e', 'En curso'), ('c', 'Cerrada')], default='m', max_length=1, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, max_length=300, verbose_name='Observaciones')),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libiapp.Socio')),
            ],
        ),
    ]
