# Generated by Django 3.0.4 on 2020-04-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='cuota',
        ),
    ]
