# Generated by Django 3.0.4 on 2020-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libiapp', '0002_remove_socio_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cuota',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='Cuota'),
        ),
    ]
