# Generated by Django 3.0.4 on 2020-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libiapp', '0003_socio_cuota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'ordering': ['numero'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
