# Generated by Django 3.0.4 on 2020-03-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200316_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
