# Generated by Django 3.0.4 on 2020-03-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduzca la lengua o idioma', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='languaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Languaje'),
        ),
    ]
