# Generated by Django 3.0.4 on 2020-03-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200324_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Seleccione un género para este libro', to='catalog.Genre'),
        ),
    ]
