# Generated by Django 3.0.4 on 2020-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200329_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('puede_crear_modificar_borrar', 'Puede crear, modificar y borrar'),)},
        ),
    ]
