# Generated by Django 3.0.4 on 2020-04-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200403_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('puede_crear_modificar_borrar', 'Puede crear, modificar y borrar'), ('can_change', 'Puede modificar'))},
        ),
    ]
